#' An R6 Class to download, view, and save a map based on desired coordinates.
#' @docType class
#' @name MapStamen
#' @usage MapStamen(left, bottom, right, top, mapType, Zoom)
#' 
#' @description MapStamen is an object generator as R6 class. The returnd object is a map
#'    which has been downloaded from mapStamen API. 
#'
#' @details MapStamen generates an object as R6 class. The returnd object is a map
#'    which has been downloaded from mapStamen API. The object
#'    will be constructed by passing the lower left and upperright coordinates of the 
#'    area of interest. Type of map and the requiered zoom can
#'     also be specified as the arguments.#'     
#'     
#'     
#' @section Methods:
#'  \describe{
#'    \item{\code{initializ(left, bottom, right, top =, mapType, Zoom)}}{This method will be initialized the class generator as the costructor is called. A new object will be generated.}
#'    \item{\code{showMap()}}{This method displays the downloaded map.}
#'    \item{\code{saveMap()}}{This method saves a png file in the working directory.}      
#'      }
#'           
#' @seealso http://maps.stamen.com
#'    
#' @return A MapStamen class object generated by R6 class "MapStamen".
#' @format \code{\link{R6Class}} object.
#' @examples myMap = MapStamen$new(left = 86.05, bottom = 27.21,
#'                                 right = 87.81, top = 28.76, mapType = "toner-lite", Zoom = 5 )
#'                                  
#' @import R6
#' @importFrom R6 R6Class
#' @import ggmap
#' @import ggplot2
#' @export
#'
MapStamen <- R6Class("MapStamen",
                     public = list(
                       
                        
                       #' @param left The lowerleft longitude of the area-box to be downloaded.
                       #' @param bottom The lowerleft latitude of the area-box to be downloaded.
                       #' @param right The upperright longitude of the area-box to be downloaded.
                       #' @param top The upperright latitude of the area-box to be downloaded.
                       #' @param mapType A string indicating the type of map("terrain", "toner",...)
                       #' @param Zoom zoom level 
                       
                       initialize = function(left = -115.60, bottom = 32.71, right = -124.30, top = 41.80,
                                             mapType = "toner-lite", Zoom = 5){
                         
                         #Returning error and stop executing as the arguments are not the correct type.
                         
                         stopifnot(is.numeric(left), length(left) == 1)
                         stopifnot(is.numeric(bottom), length(bottom) == 1)
                         stopifnot(is.numeric(right), length(right) == 1)
                         stopifnot(is.numeric(top), length(top) == 1)
                         stopifnot(is.numeric(Zoom), length(Zoom) == 1)
                         stopifnot(is.character(mapType))
                         
                         
                         # Assigning the arguments to the private fields 
                         private$.left <- left
                         private$.bottom <- bottom
                         private$.right <- right
                         private$.top <- top
                         private$.mapType <- mapType
                         private$.zoom <- Zoom
                         
                         # Downloading the map
                         private$getMap()
                         
                       },
                       
                       # Method to display the downloaded map
                       showMap = function(){
                         
                         
                         longitude = c(private$.left, private$.right)
                         latitude = c(private$.bottom, private$.top)
                         sites = data.frame(Longitude = longitude, Latitude = latitude)
                         
                         ggmap(private$.myMap, legend = "right") +
                           geom_point(data = sites, aes(x = Longitude, y = Latitude),
                                      size = 2, shape=19)
                         
                       },
                       
                       #Method to save the downloaded map as a png file.
                       saveMap = function(){
                         
                         self$showMap()
                         ggsave(filename="myMap.png",
                                width=6, height=6, units = "in")
                         
                       },
                       
                       #Method to plot AQI data on top of the map
                       bubble = function() {
                         data5 <- read.csv2("aqi2019.csv", sep = ",")


                         gooddays <- as.numeric(data5$Good)
                         moderatedays <- as.numeric(data5$Moderate)
                         unhealthy <- data.frame("Somewhat Unhealthy" = data5$Unhealthy.for.Sensitive.Groups,
                                                 "Unhealthy" = data5$Unhealthy,
                                                 "Very Unhealthy" = data5$Very.Unhealthy,
                                                 stringsAsFactors = FALSE)
                         unhealthy <- sapply(unhealthy, as.numeric)
                         nothealthy <- rowSums(unhealthy)
                         latit <- data5$latitude
                         longi <- data5$longitude
                          
                         goodplot <- data.frame(longi = longi, latit = latit, gooddays = gooddays, moderatedays = moderatedays, nothealthy = nothealthy)

                         #Plots HEALTHY days with green bubbles
                        ggmap(private$.myMap) + ggplot(data = goodplot, mapping =  aes(x = longi, y = latit, size = gooddays)) +
                           geom_point(color = "Black", shape = 21, fill = "Green", stroke = 2, alpha = 0.5)+
                           xlab("Longitude")+ ylab("Latitude") +
                           ggtitle("Number of good days in California counties - 2019")+
                           scale_size(range = c(5,30))

                         #Plots MODERATE days with orange bubbles
                         # plot2 = ggplot(data = goodplot, mapping =  aes(x = longi, y = latit , size = moderatedays)) +
                         #   geom_point(color = "Black", shape = 21, fill = "Orange", stroke = 2, alpha = 0.5)+
                         #   xlab("Longitude")+ ylab("Latitude") +
                         #   ggtitle("Number of moderate days in California counties - 2019")+
                         #   scale_size(range = c(5,30))
                         # 
                         # 
                         # #Plots UNHEALTHY days with red bubbles
                         # plot3 = ggplot(data = goodplot, mapping =  aes(x = longi, y = latit, size = nothealthy)) +
                         #   geom_point(color = "Black", shape = 21, fill = "Red", stroke = 2, alpha = 0.5)+
                         #   xlab("Longitude")+ ylab("Latitude") +
                         #   ggtitle("Number of unhealthy days in California counties - 2019")+
                         #   scale_size(range = c(5,30))
                         
                       }),
                       
                       private = list(
                         .left = NA,
                         .bottom = NA,
                         .right = NA,
                         .top = NA,
                         .zoom = NA,
                         .mapType = NA,
                         .myMap = NA,
                         # Get method to download the map from mapStamen API.
                         getMap = function(){
                           private$.myMap <- get_stamenmap(c(private$.left, private$.bottom,
                                                             private$.right , private$.top ),
                                                           maptype = private$.mapType,
                                                           crop = TRUE, zoom = private$.zoom)
                           
                           self
                         }
                         
                       )
                     )
                     
                     
                     
                     